#startup settings
watch.worldsettings.xSize = 47
watch.worldsettings.ySize = 19
watch.worldsettings.lifePresSeeded = true
watch.startup.persistent = false
watch.startup.processingTimer = 10
watch.startup.turnTimer = 10
watch.startup.continentalshiftTimer = 30
watch.startup.saveTimer = 60
watch.startup.prefix = DEV_

#continental drift variables
watch.continentalshift.driftVelocity = 1
watch.continentalshift.driftFlux = 1
watch.continentalshift.numberOfMantlePlumes = 3
watch.continent.volcano.buildup.minimum = 10000
watch.continent.volcano.turn-limit = 40
watch.continent.splitter = false
watch.continent.water.erosion.strength = 10
watch.continent.land.erosion.strength = 10
watch.continent.land.erosion.max = 10000
watch.continent.land.erosion.min = 1000