#startup settings
watch.worldsettings.xSize = 158
watch.worldsettings.ySize = 72
watch.worldsettings.lifePresSeeded = true
watch.worldsettings.numberOfContinents = 9
watch.startup.persistent = true
watch.startup.processingTimer = 60
watch.startup.turnTimer = 60
watch.startup.continentalshiftTimer = 60
watch.startup.saveTimer = 600

# World height definitions in meters
watch.oceanHeight = 1000
watch.seaHeight = 2000
watch.coastalHeight =3000
watch.plainsHeight = 4000
watch.hillHeight = 5000
watch.mountainHeight = 6000

#continental drift variables
watch.continentalshift.driftVelocity = 1
watch.continentalshift.driftFlux = 1
watch.continentalshift.numberOfMantlePlumes = 6
watch.continent.volcano.buildup.minimum = 1000
watch.continent.volcano.height.maximum = 6000
watch.continent.volcano.turn-limit = 40
watch.continent.volcano.number.minimum = 10
watch.continent.mantle-plume.amount.minimum = 6
watch.continent.mantle-plume.turn-limit = 40
watch.continent.splitter = false
watch.continent.water.erosion.multiplier = 1000
watch.continent.water.erosion.strength = 10
watch.continent.land.erosion.strength = 10
watch.continent.land.erosion.max = 10000
watch.continent.land.erosion.min = 1000
watch.continentalshift.continentalToOcceanicRatio = 3

# erosion settings in meters
watch.erosion.minHeightDifference = 1000
watch.erosion.max = 1000000