#startup settings
watch.worldsettings.xSize = 198
watch.worldsettings.ySize = 92
watch.startup.persistent = true
watch.startup.processingTimer = 10
watch.startup.turnTimer = 10
watch.startup.continentalshiftTimer = 30
watch.startup.saveTimer = 240

#continental drift variables
watch.continentalshift.driftVelocity = 1
watch.continentalshift.driftFlux = 1
watch.continentalshift.numberOfMantlePlumes = 5
watch.continent.volcano.buildup.minimum = 10000
watch.continent.volcano.turn-limit = 40
watch.continent.mantle-plume.turn-limit = 40
watch.continent.splitter = false
watch.continent.water.erosion.strength = 10
watch.continent.land.erosion.strength = 10
watch.continent.land.erosion.max = 10000
watch.continent.land.erosion.min = 1000