package com.watchers.model.climate;

public enum ClimateEnum {
    OCEAN, SEA, COASTAL,
    POLAR_ARID, POLAR_SEMI_ARID, POLAR_HUMID, POLAR_WET,
    TEMPERATE_ARID, TEMPERATE_SEMI_ARID, TEMPERATE_HUMID, TEMPERATE_WET,
    TROPICAL_ARID, TROPICAL_SEMI_ARID, TROPICAL_HUMID, TROPICAL_WET
}