package com.watchers.model.environment;

public enum BiomeTypeEnum {
    OCEAN, SEA, COASTAL,

    POLAR_MOUNTAIN_DESERT, POLAR_MOUNTAIN_TUNDRA, POLAR_MOUNTAIN_TAIGA,
    POLAR_HILL_DESERT, POLAR_HILL_TUNDRA, POLAR_HILL_TAIGA,
    POLAR_PLAIN_DESERT, POLAR_PLAIN_TUNDRA, POLAR_PLAIN_TAIGA,

    TEMPERATAE_MOUNTAIN_DESERT, TEMPERATE_MOUNTAIN_GRASSLAND,  TEMPERATE_MOUNTAIN_FOREST,
    TEMPERATE_HILL_DESERT, TEMPERATE_HILL_GRASSLAND, TEMPERATE_HILL_FOREST,
    TEMPERATE_PLAIN_DESERT, TEMPERATE_PLAIN_GRASSLAND, TEMPERATE_PLAIN_FOREST,

    TROPICAL_MOUNTAIN_DESERT, TROPICAL_MOUNTAIN_SAVANAH, TROPICAL_MOUNTAIN_JUNGLE,
    TROPICAL_HILL_DESERT, TROPICAL_HILL_SAVANAH, TROPICAL_HILL_JUNGLE,
    TROPICAL_PLAIN_DESERT, TROPICAL_PLAIN_SAVANAH, TROPICAL_PLAIN_JUNGLE
}
